### ISSUE TITLE
Future Maintenance?

### ISSUE THREAD

**Issue by dk0r** [pveierland/aix-weather-widget#1]
>  I can only allocate a minimal amount of time to this app and will not spend further time developing it, but please email me via Google Play if you wish to become a maintainer or plan an improvement of the app.

I've been using aix-weather-widget-donate for the past two years and still haven't found a replacement! 
Any more details to what extent you'll maintain this project? Do you see foresee major breaking changes in future android api's?

**Comment by rivonia** [comment]
> I've been using aix-weather-widget-donate for the past two years and still haven't found a replacement!

Try [Meteogram Weather Charts](https://play.google.com/store/apps/details?id=com.cloud3squared.meteogram)... with just a couple of changes in the settings you can get something that looks very similar to Aix (if that's what you want):

![screenshot_20170706-090153](https://user-images.githubusercontent.com/29942149/27901592-84c14860-622a-11e7-99f1-619d158245e2.jpg)

The top one is Meteogram Weather Charts, the bottom one is Aix.

Or you can be radical and try a completely different look... [pretty much anything is possible](https://trello.com/b/ST1CuBEm/meteogram-weather-charts).

**Comment by pveierland** [comment]
> Any more details to what extent you'll maintain this project?

I will only keep fixing things which breaks the app, e.g. changes in the APIs the app uses etc.

> Do you see foresee major breaking changes in future android api's?

The app should be able to function on newer versions of Android, however several hacks were used to make such a graphical widget possible. What I believe was a fairly unique feature of Aix at the time it was made was pixel-perfect rendering through a device calibration feature in order to find the exact pixel space available. The Android API did not offer a way to discover the exact pixel space available to a widget to my knowledge, and I'm still not certain if it does.

> Try Meteogram Weather Charts... with just a couple of changes in the settings you can get something that looks very similar to Aix (if that's what you want):

Meteogram Weather Charts looks very nice and it is the closest widget I've seen to Aix. It would be interesting to know exactly how it is rendered.
