### ISSUE TITLE
Widget not using full width?

### ISSUE THREAD

**Issue by sddakoty** [pveierland/aix-weather-widget#10]
Since the latest update (0.1.9.19-33, or one of the prior), I noticed the widget is not using the full screen width (portrait mode) anymore. As a result, there are only three hours displayed: 01, 07, 13.

Once this was able to display at least every 2h and use the full width. Why has there been a change??

If that matters, using Android 6.0.1

**Comment by pveierland** [comment]
The Aix Weather Widget layout was changed in the recent update as the app had to target a later version of Android due to a new Google Play requirement. A change in the Android SDK has changed how widget sizes are calculated, and this results in a different effective size.

To fill the desired space on your homescreen, I would suggest installing a custom launcher such as Nova Launcher, which will allow you to resize the widget as desired.

After resizing the widget, enter the Aix Weather Widget configuration screen, and select "Device Profiles", then "Activate device specific dimensions". Then use the calibration feature to identify the correct screen space available to the widget in pixels. There is an old guide describing this process here:

https://www.youtube.com/watch?v=gcvM2qS4MVM

This should allow you to size the Aix Weather Widget to your desire such that it uses all available screen space.

**Comment by sddakoty** [comment]
Ok that worked regarding having the 2h grid back. Unfortunately it's not as pretty as before and looks a bit blury. But as you'll probably have no chance fixing it, I could live with it.
